version: "3"
services:
  backend:
    build: ./
    container_name: comics-api-dpwfsrjs
    ports: 
      - 8080:8080
    environment:
      MYSQL_HOST: 
      MYSQL_USER: root
      MYSQL_PASSWORD: root@1.0
      MYSQL_DATABASE: comics
      MYSQL_PORT: 3306
      NOTIFICATION_PORT: 587
      NOTIFICATION_HOST: backend
      NOTIFICATION_USER: comicsdpwfsrjs@gmail.com
      NOTIFICATION_PASS: none
      NOTIFICATION_SERVICE: gmail
      PORT: 8080