version: "3"
services:
  db_comics:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@1.0
      MYSQL_DATABASE: comics
    ports: 
      - 3306:3306
    volumes:
      - /data/comics-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  comics-db-data: